# 服务端口
server:
  port: 8201
# 服务名
spring:
  application:
    name: service-hosp
  # 环境设置：dev、test、prod
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    #password: ct19991207
    password: 123456
    url: jdbc:mysql://192.168.126.128:3306/yygh_hosp?characterEncoding=utf-8&useSSL=false
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    # nacos服务地址
    nacos:
      discovery:
        server-addr: 192.168.126.128:8848
        group: yygh
    #设置sentinel地址
    sentinel:
      transport:
        dashboard: http://192.168.126.128:8858
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: yygh_hosp


#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
#配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

#开启sentinel
feign:
  sentinel:
    enabled: true
