# 服务端口
server:
  port: 8160
# 服务名
spring:
  application:
    name: service-user
  # 环境设置：dev、test、prod
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    #password: ct19991207
    password: 123456
    url: jdbc:mysql://192.168.126.128:3306/yygh_user?characterEncoding=utf-8&useSSL=false
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
      shutdown-timeout: 100
  cloud:
    # nacos服务地址
    nacos:
      discovery:
        server-addr: 192.168.126.128:8848
        group: yygh
    #设置sentinel地址
    sentinel:
      transport:
        dashboard: http://192.168.126.128:8858


#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
#配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

#开启sentinel
feign:
  sentinel:
    enabled: true
wx:
  open:
    app_id: wxed9954c01bb89b47
    app_secret: a7482517235173ddb4083788de60b90e
    redirect_url: http://localhost:8160/api/ucenter/wx/callback
yygh:
  baseUrl: http://localhost:3030
