# 服务端口
server:
  port: 8204
# 服务名
spring:
  application:
    name: service-msm
  # 环境设置：dev、test、prod
  profiles:
    active: dev
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
      shutdown-timeout: 100
  cloud:
    # nacos服务地址
    nacos:
      discovery:
        server-addr: 192.168.126.128:8848
        group: yygh

# 腾讯云短信服务配置
# sms-config:
  # 腾讯云账户密钥对 secretId 和 secretKey
  # secretId: AKIDb1A2ez3qMcbJkunPkpc8NL2SaR2MPBgu
  # secretKey: yf4E8l7D2arra2DG2XkgLjqfEWWFiupT
  # 短信应用appId和appKey
  # appId: 1400620674
  # appKey: 1888fd31686c53372009656f3ce724bb
  # 签名
  # smsSign: funnykeke
  # 过期时间
  # endPoint: 10  # 10min
  # 模板id
  # templateId: 1273584










